/*
 * MIT License
 *
 * Copyright (c) 2024 Jackson Brienen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.github.kentlakecs.data.io;

import java.lang.reflect.Type;
import com.github.kentlakecs.data.*;
import com.google.gson.*;

/**
 * {@link JsonSerializer} to serialize {@link CodeLesson} objects
 * 
 * @author Jackson Brienen
 * @version 1.0
 */
class CodeLessonSerializer implements JsonSerializer<CodeLesson> {

    /**
     * Constant CodeLesson Json Property names used for {@link JsonObject#add(String, JsonElement)} and {@link JsonObject#addPoperty}
     */
    private static final String NAME = "name",
                                DESCRIPTION = "description",
                                VISUAL = "visual",
                                METHOD_NAME = "methodName",
                                PARAMETERS = "parameters",
                                RETURN_TYPE = "returnType",
                                TEST = "test";

    /**
     * Creates a {@link JsonElement} representing the given {@link CodeLesson}
     * @param src a {@link CodeLesson}
     * @param typeOfSrc {@link CodeLesson#getClass()}
     * @param context The default {@link JsonSerializationContext} generated by some {@link GsonBuilder}
     * @return a {@link JsonElement} representing the given {@link CodeLesson}
     */
    @Override
    public JsonElement serialize(CodeLesson src, Type typeOfSrc, JsonSerializationContext context) {
        JsonObject o = new JsonObject();

        // Lesson
        o.addProperty(NAME, src.getName());
        o.addProperty(DESCRIPTION, src.getDescription());
        o.addProperty(VISUAL, false);

        // Code Lesson
        o.addProperty(METHOD_NAME, src.getMethodName());
        o.add(PARAMETERS, context.serialize(src.getParameters(), Parameter[].class));
        o.add(RETURN_TYPE, context.serialize(src.getReturnType()));
        o.addProperty(TEST, src.getTest());

        return o;
    }
    
}
